// <auto-generated />
namespace CodeIt.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Usershasmanysubmissions : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Usershasmanysubmissions));
        
        string IMigrationMetadata.Id
        {
            get { return "201703260956474_Users has many submissions."; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
